name: "APDT Examples::Basic Flashcard"
fields:
  - "Front"
  - "Back"
templates:
  - name: "Basic"
    qfmt: |
      <div>{{Front}}</div>
    afmt: |
      {{FrontSide}}
      <hr id=answer>
      <div>{{Back}}</div>
